[package]
name = "catr"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.23"
rand = "0.9.1"
anyhow = "1.0.98"
pretty_assertions = "1.4.1"

[dev-dependencies]
assert_cmd = "2.0.16"
predicates = "3.1.3"
