[build]
target = "index.html"
dist = "dist"

[watch]
watch = ["src", "assets"]

[[hooks]]
stage = "pre_build"
command = "sh"
command_arguments = ["-c", "npx tailwindcss -i ./assets/css/main.css -o ./dist/output.css"]

